services:
  postgres:
    image: postgres:16
    container_name: folders-postgres
    environment:
      POSTGRES_DB: folders
      POSTGRES_USER: folders
      POSTGRES_PASSWORD: folders
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: folders-mongodb
    environment:
      MONGO_INITDB_DATABASE: proyectoSpringboot
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  postgres-data:
  mongodb-data:
