services:
  postgres:
    image: postgres:16
    container_name: folders-postgres
    environment:
      POSTGRES_DB: folders
      POSTGRES_USER: folders
      POSTGRES_PASSWORD: folders
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: folders-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: folders
      MONGO_INITDB_ROOT_PASSWORD: folders
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data: