app.storage=postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/folders
spring.datasource.username=folders
spring.datasource.password=folders
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
