spring.application.name=folders-project
server.port=8080

## custom y collections

app.tree-strategy=collections

## memory, postgres y mongodb (Con minusculas y no es postgresSQL es postgres )
## Ademas cuidado con los puertos porque si tienen algun proyecto corriendo en el puerto predefino de Springboot 8080
## Les va a tirar un error de que el puerto esta en uso. Igual con el puerto del mismo postgres el 5433

app.storage=mongodb

spring.data.mongodb.uri=mongodb://Progra3:Progra3@localhost:27017/proyectoSpringboot?authSource=admin

spring.datasource.url=jdbc:h2:mem:folders
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never


