spring.application.name=programacion3.proyectofinal

spring.data.mongodb.uri=mongodb://localhost:27017/proyectoSpringboot

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration










