app.storage=postgres

# Config de la DB
spring.datasource.url=jdbc:postgresql://localhost:5433/folders
spring.datasource.username=folders
spring.datasource.password=folders
spring.datasource.driver-class-name=org.postgresql.Driver

# Config para que hiberne
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inicializar 
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.data-locations=classpath:db/seed.sql
