spring.application.name=folders-project
server.port=8080

app.tree-strategy=collections
app.storage=mongodb

spring.data.mongodb.uri=mongodb://Progra3:Progra3@localhost:27017/proyectoSpringboot?authSource=admin

spring.datasource.url=jdbc:h2:mem:folders
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never


